default: &defaults
  display_user_avatars: true
  default_user_avatar: 'identicon'
  user_avatar_api_url: 'https://wingolfsplattform.org/avatars?email=:email&size=:size'
  enable_custom_stylesheet: true
  custom_stylesheet_url:
  enable_custom_javascript: false
  custom_javascript_url:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
