default: &defaults
  display_user_avatars: true
  default_user_avatar: 'identicon'
  user_avatar_api_url: 'https://wingolfsplattform.org/avatars?email=:email&size=:size'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
